### ISSUE TITLE
support values out of 0..1 range

### ISSUE THREAD

**Issue by paulirish** [matthewlein/Ceaser#1]
opera and FF ( i think ) support cubic bezier functions above 1 and below 0.
webkit has agreed and will implement that (if they didn't already)

so yeah.. lets add somma dat

cc @leaverou

**Comment by matthewlein** [comment]
I know FF has for some time. And bounce is one of my guilty pleasures...but this is the only Webkit bug tracked using 'cubic-bezier' and its still open.
https://bugs.webkit.org/show_bug.cgi?id=45761

Do you have any other info?

Due to the copy/paste nature of it, I'd rather not provide code that does nothing in webkit until its in a stable chrome/safari build. Then use at your own risk. If webkit treated any value > 1 as 1 and < 0 as 0, then I'd have something to work with, but they dropped the ball on this one. And its lame to plaster a sign that says "this code won't work in Safari 5.1 and below and Chrome 15 and below. Right?

Sooo...maybe I build a fancier gizmo that does up to 2 or 3(!) range but not release it for awhile.

thoughts?

**Comment by paulirish** [comment]
iunno. i think a checkbox that says "opt into browser inconsistency" and tells you whats up woudl be best

btw if you check lea's twitter you'll see a dribbble recently that indicates she has something up her sleeves along these lines :o

**Comment by matthewlein** [comment]
Yes it would have to be opt in.

Maybe its best for now to allow > 1, but make sure that -webkit- doesn't output numbers > 1. It would be great if webkit allowed > 1 when they remove the flag, so you can do < 1 for -webkit and > 1 for standards transition.

How about you make chrome do that :D

**Comment by LeaVerou** [comment]
Yup, that's what I do in the one I've been making for the past few days. It includes a warning when the user goes out of range, and offers an alternative for Webkit (currently clips the values to 0-1 which is not ideal, but oh well). You could try that :)

**Comment by paulirish** [comment]
relevant: https://github.com/Modernizr/Modernizr/pull/376/files

**Comment by matthewlein** [comment]
oh nice!

.cubicbezierrange {
    fun stuff
}
.no-cubicbezierrange {
    less fun stuff
}

That is a good solution for the interim (years).

**Comment by LeaVerou** [comment]
Years? Come on, Peter Beverloo already submitted a patch to Webkit. If it gets integrated in a month, my guess is in around a year we'll be able to use it without fallbacks, at least for desktop.

**Comment by paulirish** [comment]
so that bug is fixed

but realized this is totally doable.. just rely on css error handling:

``` css
-webkit-transition: all 500ms cubic-bezier(.17, .67, .8, 1);
-webkit-transition: all 500ms cubic-bezier(.17, .67, .8, 1.7);
```

this'll use the >1 value if its supported.. otherwise clamped to 1.

boom boom

**Comment by matthewlein** [comment]
You sir, are a genius. And...I'm mad at myself for not putting that together, considering how many times I've abused that for gradients, etc.

The proof is in the pudding:
http://jsfiddle.net/matthewlein/3LL4m/7/

I will find time this week to juice up ceaser with this awesome sauce.

Case closed.
